[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "snapper-ont"
authors = [{name = "Dmitry N. Konanov", email = "konanovdmitriy@gmail.com"}]
dynamic = ["version", "description"]
